
version: 2

models:
  - name: users
    description: "One unique user per row, and user attributes."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: users_usa
    description: "One unique user per row, USA users only."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: users_country_conversion
    description: "'users' data, using a Macro adds a column converting country_code to country name."
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
